version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: my_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - mongo_data_new:/data/db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=mydb
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
    volumes:
      - clickhouse_data:/var/lib/clickhouse
  tabix:
      image: spoonest/clickhouse-tabix-web-client:latest
      container_name: tabix
      ports:
        - "8080:8080"
      environment:
        - CLICKHOUSE_HOST=clickhouse
        - CLICKHOUSE_PORT=8123
        - CLICKHOUSE_USER=default
        - CLICKHOUSE_PASSWORD=mypassword
      depends_on:
        - clickhouse

volumes:
  mongo_data_new:
  redis_data:
  clickhouse_data: